export const Foodimages = [
  "/food images/Biryani.png",
  "/food images/Burger.png",
  "/food images/Cake.png",
  "/food images/Chinese.png",
  "/food images/CholeBhature.png",
  "/food images/Dhokla.png",
  "/food images/Dosa.png",
  "/food images/Kachori.png",
  "/food images/Momo.png",
  "/food images/Noodles.png",
  "/food images/Pasta.png",
  "/food images/Pastry.png",
  "/food images/Patty.png",
  "/food images/PavBhaji.png",
  "/food images/Pizza.png",
  "/food images/Rolls.png",
  "/food images/Samosa.png",
  "/food images/Shake.png",
  "/food images/Shawarma.png",
  "/food images/Tea.png",
];
